### ISSUE TITLE
Custom error descriptions

### ISSUE THREAD

**Issue by bajtos** [moll/js-must#14]
Please add support for custom error descriptions, it makes assertion messages much more useful.

Consider the following code I would write with chai:

```js
it('deletes files', function() {
   var configPath = // resolve
   var cachePath = // resolve

  // this is the method under test, it deletes config and cache
  removeEntry();

   expect(fs.existsSync(configPath), 'config exists').to.be.false();
   expect(fs.existsSync(cachePath), 'cache exists').to.be.false();
});
```

When I run it using must, the error message is not very helpful:

```
AssertionError: true must be false
  at removeentry.test.js:8
  etc.
```

I would like to get enough information to know why the test failed, without the need to look up the line in the source code that executed the assertion

```
AssertionError: config exists: true must be false
 at removeentry.test.js:8
 etc.
```

I am happy to submit a pull request if you are willing to accept this feature.

**Comment by McDonnellDean** [comment]
Perhaps to add some context around this feature as I would like it also.

I would also like it because it simplifies tests like ensuring all items in a collection have a given field or value. Currently there is no good way to find out which element in a collection failed without resorting to console.log.

So something like:
```js
_.forEach(elements, function(element) {
   expect(element.id, 'Id: ' + element.id).to.be.falsy();
});
```

While I agree mostly with the one method per assertion rule, dealing with collections tends to mean asserting on each item in said collection.

**Comment by michaeljones** [comment]
Very happy to have switched to `must` as I strongly agree with avoiding the `undefined` issues in chai. I was surprised to find that `must` doesn't support extra messages though. I've got a similar situation with a `false should equal true` style error message which I've managed to improve a little by juggling what I am testing but it means there is no room for providing additional contextual information about what inputs lead to a failure as far as I can tell. It means that a test failure is going to immediately require another run with print statements rather than the test assertion being able to provide useful information.

Maybe I'm doing it wrong though? Should I be running all my tests through node-inspector or something similar to debug the results rather than expect to have enough information from the test failure itself?

The example at the top would be helped by the framework printing the failing line but my failing line is:

```
        const spec = interfaces[module].methods[func];
        const result = complianceChecker.check(spec, data);
        expect(result.message).to.be.undefined()
```

Which has no visible information that is of use. I kind of need to know the value of spec & data to understand what has gone wrong. I started with `expect(result.success).eql(true)` but that has almost no information in the output so I've moved to this but the result is still less than desirable as I now get `AssertionError: "Missing attribute: id" must be undefined` which is only useful if I remember to ignore the `must be undefined` bit and work with the message I want. 

Considering a selling point in your readme is 'Human readable error messages', it might be worth allowing humans to make them more readable when it suits them.

All that said, I've never written an assertion framework before and I'm very grateful for the work you've done! Cheers!

**Comment by moll** [comment]
Good news, everyone! I'm sold for now. :innocent:

A `message` argument for `demand`/`expect` style invocation is there for you to give a go:
```js
var demand = require("must")
demand(undefined, "The undefined undefineds").be.undefined()
```

It's up as v0.13.1 and docs at https://github.com/moll/js-must/blob/master/doc/API.md#Must. Shoot a message if it's not behaving as expected.

PS. Should really cut v1 at some point, too. This isn't Google with its indefinite betas after all. ^_^

**Comment by michaeljones** [comment]
Great news! Thank you!
