### ISSUE TITLE
Not working with other promises libraries

### ISSUE THREAD

**Issue by albertorestifo** [moll/js-must#31]
I'm using Bluebird, I've replaced the `Promise` object globally.

This example test fails:

![image](https://cloud.githubusercontent.com/assets/1037048/9308970/360dfb60-4507-11e5-9f9f-c54a56ddd719.png)

![image](https://cloud.githubusercontent.com/assets/1037048/9308986/46c37fe8-4507-11e5-9539-03976b32180e.png)

**Comment by moll** [comment]
Hey! Sorry you're having trouble. I have a sneaking suspicious it's because the version with promises isn't the stable version just yet. I meant to release it as a stable briefly after adding promise support, but got sidetracked. :innocent: If you do `npm install must@v0.13.0-beta1`, does that solve the problem?

**Comment by albertorestifo** [comment]
Worked like a charm. 

Thanks for the quick reply and will look forward to the stable release :balloon:

**Comment by moll** [comment]
Yay. :)
